export default [
  'strapi::logger',
  'strapi::errors',
  'strapi::security',
  {
    name: 'strapi::cors',
    config: {
      origin: [
        'http://localhost:3000',
        'http://localhost:5173', 
        'http://localhost:5174',
        'https://prompt-analyzer-client.vercel.app', 
        'https://prompt-pal-front-end.vercel.app',
        'https://edu-sync-5s2x-git-feat-prompt-pal-i-1098a1-shuaybcodes-projects.vercel.app',
        'edu-sync-5s2x-git-feat-prompt-pal-i-1098a1-shuaybcodes-projects.vercel.app',
        'edu-sync-5s2x-o0oi0mnj8-shuaybcodes-projects.vercel.app',
        'edu-sync-5s2x-git-testing-shuaybcodes-projects.vercel.app',
      ],
      credentials: true,
      headers: ['*'],
      methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
    },
  },
  'strapi::poweredBy',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
